# Generated by Django 6.1.1 on 2026-09-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
